import { useState } from 'react'
import { Card, CardTitle } from '../components/Card'
import { useFinance } from '../hooks/useFinance'
import { useBackendAuthOptional } from '../components/BackendAuthContext'
import './Imports.css'

type UploadResult = { batchId: string; fileName: string; totalRows: number; addedCount: number; duplicateCount: number; errors?: Array<{ row: number; error: string }>; message: string }
type Row = { id: string; title: string; amountMinor: string; occurredOn: string; status: string; validationErrors: string[] }
const minorAmount = (value: string) => (Number(value) / 100).toFixed(2)
export function Imports() {
  const finance = useFinance(); const backend = useBackendAuthOptional(); const [file, setFile] = useState<File | null>(null); const [upload, setUpload] = useState<UploadResult | null>(null); const [rows, setRows] = useState<Row[]>([]); const [accountId, setAccountId] = useState(finance.state.accounts[0]?.id ?? ''); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  async function uploadCsv(event: React.FormEvent) { event.preventDefault(); if (!backend) { setError('CSV imports are available in backend mode.'); return } if (!file) { setError('Choose a CSV file first.'); return } setError(null); const data = new FormData(); data.append('file', file); const response = await fetch('/api/v1/imports/csv/upload', { method: 'POST', credentials: 'include', body: data }); const body = await response.json(); if (!response.ok) { setError(body.error?.message ?? 'Upload failed.'); return } setUpload(body); const detail = await fetch(`/api/v1/imports/batches/${body.batchId}/transactions`, { credentials: 'include' }); setRows(await detail.json()); setMessage(body.message) }
  async function commit() { if (!upload || !accountId) return; const response = await fetch(`/api/v1/imports/batches/${upload.batchId}/commit`, { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ matchedAccountId: accountId }) }); const body = await response.json(); if (!response.ok) setError(body.error?.message ?? 'Commit failed.'); else setMessage(`Committed ${body.committedCount} transaction(s).${body.errors?.length ? ` ${body.errors.length} row(s) need attention.` : ''}`) }
  return <div className="imports-page"><div className="page-head"><div><p className="eyebrow">Track</p><h1 className="page-title">Import transactions</h1><p className="page-subtitle">Upload a CSV, review staged rows, then commit them to the ledger.</p></div></div><Card><CardTitle>1. Upload CSV</CardTitle><p className="form-help">Required columns: date, amount, description. Amounts must be positive; income detection and rules are applied during commit.</p><form className="imports-form" onSubmit={uploadCsv}><label>CSV file<input type="file" accept=".csv,text/csv" onChange={(event) => setFile(event.target.files?.[0] ?? null)} required /></label><button className="btn btn--primary" type="submit">Upload and preview</button></form>{message && <p role="status" className="form-help">{message}</p>}{error && <p role="alert" className="tx-error">{error}</p>}</Card>{upload && <Card><CardTitle>2. Review staged rows</CardTitle><p className="form-help">{upload.addedCount} added · {upload.duplicateCount} duplicates skipped · {upload.totalRows} source rows</p><div className="import-table-wrap"><table className="import-table"><thead><tr><th>Date</th><th>Description</th><th>Amount</th><th>Status</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.occurredOn.slice(0, 10)}</td><td>{row.title}</td><td>{minorAmount(row.amountMinor)}</td><td>{row.status}{row.validationErrors.length ? `: ${row.validationErrors.join(', ')}` : ''}</td></tr>)}</tbody></table></div><div className="imports-commit"><label>Post to account<select value={accountId} onChange={(event) => setAccountId(event.target.value)}>{finance.state.accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><button className="btn btn--primary" type="button" onClick={() => void commit()} disabled={!rows.length}>Commit eligible rows</button></div></Card>}</div>
}
