import { useEffect, useState } from 'react'
import { Card, CardTitle } from '../components/Card'
import { useFinance } from '../hooks/useFinance'
import { useBackendAuthOptional } from '../components/BackendAuthContext'
import { formatMoney } from '../utils/currency'
import './Reconciliation.css'

type RecordItem = { id: string; accountId: string; statementDate: string; statementBalanceMinor: string; calculatedBalanceMinor: string; differenceMinor: string; status: string }
export function Reconciliation() {
  const finance = useFinance(); const backend = useBackendAuthOptional()
  const [accountId, setAccountId] = useState(finance.state.accounts[0]?.id ?? '')
  const [date, setDate] = useState(finance.todayIso); const [balance, setBalance] = useState(''); const [records, setRecords] = useState<RecordItem[]>([]); const [result, setResult] = useState<RecordItem | null>(null); const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (!backend) return; fetch('/api/v1/reconciliations', { credentials: 'include' }).then((r) => r.json()).then(setRecords).catch(() => setError('Could not load reconciliation history.')) }, [backend])
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(null); setResult(null); if (!backend) { setError('Reconciliation is available in backend mode.'); return } const response = await fetch('/api/v1/reconciliations', { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ accountId, statementDate: date, statementBalanceMinor: Math.round(Number(balance) * 100).toString() }) }); const body = await response.json(); if (!response.ok) { setError(body.error?.message ?? 'Could not reconcile account.'); return } setResult(body); setRecords((current) => [body, ...current]) }
  const accountName = (id: string) => finance.state.accounts.find((account) => account.id === id)?.name ?? id
  return <div className="reconciliation-page"><div className="page-head"><div><p className="eyebrow">Track</p><h1 className="page-title">Reconciliation</h1><p className="page-subtitle">Compare a statement balance with your cleared ledger.</p></div></div><Card><CardTitle>Reconcile an account</CardTitle><form className="reconciliation-form" onSubmit={submit}><label>Account<select value={accountId} onChange={(event) => setAccountId(event.target.value)} required>{finance.state.accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label>Statement date<input type="date" value={date} onChange={(event) => setDate(event.target.value)} required /></label><label>Statement balance<input inputMode="decimal" value={balance} onChange={(event) => setBalance(event.target.value)} placeholder="0.00" required /></label>{error && <p className="tx-error" role="alert">{error}</p>}<button className="btn btn--primary" type="submit">Compare balance</button></form>{result && <div className={`reconciliation-result reconciliation-result--${result.status}`} role="status"><strong>{result.status === 'reconciled' ? 'Reconciled' : 'Difference found'}</strong><span>Statement: {formatMoney(Number(result.statementBalanceMinor) / 100)}</span><span>Calculated: {formatMoney(Number(result.calculatedBalanceMinor) / 100)}</span><span>Difference: {formatMoney(Number(result.differenceMinor) / 100)}</span></div>}</Card><Card><CardTitle>History</CardTitle>{records.length === 0 ? <p className="faint">No reconciliation records yet.</p> : <ul className="reconciliation-list">{records.map((record) => <li key={record.id}><div><strong>{accountName(record.accountId)}</strong><small>{record.statementDate} · {record.status}</small></div><span className="num">{formatMoney(Number(record.differenceMinor) / 100)}</span></li>)}</ul>}</Card></div>
}
