import { useEffect, useState, type FormEvent } from 'react'
import { Card, CardTitle } from '../components/Card'
import { PageHeader } from '../components/PageHeader'
import { useConfirm } from '../hooks/useConfirm'
import { useBackendAuthOptional } from '../components/BackendAuthContext'
import type { paths } from '../api.generated'
import './Rules.css'

type Rule = paths['/rules']['get']['responses'][200]['content']['application/json'][number]
type CreateRuleRequest = paths['/rules']['post']['requestBody']['content']['application/json']
const initial = { name: '', merchantContains: '', normalizedMerchant: '', addTags: '', note: '' }
export function Rules() {
  const backend = useBackendAuthOptional(); const [rules, setRules] = useState<Rule[]>([]); const [form, setForm] = useState(initial); const [error, setError] = useState<string | null>(null); const { confirm, dialog: confirmDialog } = useConfirm()
  useEffect(() => { if (!backend) return; fetch('/api/v1/rules', { credentials: 'include' }).then(async (response) => { if (!response.ok) throw new Error('rules unavailable'); return response.json() as Promise<Rule[]> }).then(setRules).catch(() => setError('Could not load transaction rules.')) }, [backend])
  async function createRule(event: FormEvent) { event.preventDefault(); setError(null); if (!form.name.trim() || !form.merchantContains.trim()) { setError('Name and merchant condition are required.'); return } if (!backend) { setError('Rules are available in backend mode.'); return } const payload: CreateRuleRequest = { name: form.name.trim(), conditions: { merchantContains: form.merchantContains.trim() }, actions: { normalizedMerchant: form.normalizedMerchant.trim() || undefined, addTags: form.addTags.split(',').map((tag) => tag.trim()).filter(Boolean), note: form.note.trim() || undefined } }; const response = await fetch('/api/v1/rules', { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) { setError('Could not save rule.'); return } const created = await response.json() as Rule; setRules((current) => [...current, created]); setForm(initial) }
  async function remove(id: string, name: string) { if (!backend || !await confirm({ title: 'Delete transaction rule?', message: `Delete “${name}”? Imported transactions will no longer use this rule.`, confirmLabel: 'Delete rule' })) return; const response = await fetch(`/api/v1/rules/${id}`, { method: 'DELETE', credentials: 'include' }); if (!response.ok) { setError('Could not delete rule.'); return } setRules((current) => current.filter((rule) => rule.id !== id)) }
  return <div className="rules-page page-stack"><PageHeader eyebrow="Automate" title="Transaction rules" description="Normalize imported transactions with explicit, reviewable conditions." /><Card><CardTitle>Create a rule</CardTitle><p className="section-description">Rules run during import in priority order. They never change balances or call AI.</p><form className="rules-form" onSubmit={createRule}><label>Name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Jollibee normalization" /></label><label>Merchant contains<input value={form.merchantContains} onChange={(e) => setForm({ ...form, merchantContains: e.target.value })} placeholder="JOLLIBEE" /></label><label>Normalize merchant to<input value={form.normalizedMerchant} onChange={(e) => setForm({ ...form, normalizedMerchant: e.target.value })} placeholder="Jollibee" /></label><label>Add tags <span className="faint">comma separated</span><input value={form.addTags} onChange={(e) => setForm({ ...form, addTags: e.target.value })} placeholder="fast-food, work" /></label><label>Note<input value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} placeholder="Optional note" /></label>{error && <p role="alert" className="tx-error">{error}</p>}<button className="btn btn--primary" type="submit">Save rule</button></form></Card><Card><CardTitle>Saved rules</CardTitle>{rules.length === 0 ? <p className="faint">No rules yet.</p> : <ul className="rules-list">{rules.map((rule) => <li key={rule.id}><div><strong>{rule.name}</strong><small>When merchant contains “{String(rule.conditions.merchantContains ?? '')}”</small></div><button className="btn btn--ghost btn--compact" type="button" onClick={() => void remove(rule.id, rule.name)}>Delete</button></li>)}</ul>}</Card>{confirmDialog}</div>
}
