import { useEffect, useState } from 'react'
import { Card, CardTitle } from '../components/Card'
import { useBackendAuthOptional } from '../components/BackendAuthContext'
import './Security.css'
type Session = { id: string; current: boolean; createdAt: string; lastSeenAt: string; expiresAt: string; userAgent?: string | null }
export function Security() { const backend = useBackendAuthOptional(); const [sessions, setSessions] = useState<Session[]>([]); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (!backend) return; fetch('/api/v1/auth/sessions', { credentials: 'include' }).then((r) => r.json()).then(setSessions).catch(() => setError('Could not load sessions.')) }, [backend])
  async function change(event: React.FormEvent) { event.preventDefault(); const response = await fetch('/api/v1/auth/change-password', { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ currentPassword, newPassword }) }); if (response.ok) { setMessage('Password changed. Other sessions were signed out.'); setCurrentPassword(''); setNewPassword(''); setSessions((current) => current.filter((session) => session.current)) } else setError('Current password was incorrect or the new password was invalid.') }
  async function revoke(id: string) { await fetch(`/api/v1/auth/sessions/${id}`, { method: 'DELETE', credentials: 'include' }); setSessions((current) => current.filter((session) => session.id !== id)) }
  if (!backend) return <div className="security-page"><Card><CardTitle>Sessions & Security</CardTitle><p className="faint">Security controls are available in backend mode.</p></Card></div>
  return <div className="security-page"><Card><CardTitle>Change password</CardTitle><form className="security-form" onSubmit={change}><label>Current password<input type="password" autoComplete="current-password" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} required /></label><label>New password<input type="password" autoComplete="new-password" minLength={8} value={newPassword} onChange={(e) => setNewPassword(e.target.value)} required /></label><button className="btn btn--primary" type="submit">Change password</button></form></Card><Card><CardTitle>Active sessions</CardTitle>{message && <p role="status">{message}</p>}{error && <p role="alert" className="tx-error">{error}</p>}<ul className="session-list">{sessions.map((session) => <li key={session.id}><div><strong>{session.current ? 'This device' : 'Other session'}</strong><small>{session.userAgent ?? 'Unknown device'} · Last active {new Date(session.lastSeenAt).toLocaleString()}</small></div>{!session.current && <button type="button" className="btn btn--ghost btn--compact" onClick={() => void revoke(session.id)}>Revoke</button>}</li>)}</ul></Card></div>
}
