import { useCallback, useEffect, useState } from 'react'
import { Card, CardTitle } from '../components/Card'
import { PageHeader } from '../components/PageHeader'
import { useConfirm } from '../hooks/useConfirm'
import { useAsyncFinanceOptional } from '../state/asyncFinanceContext'
import { localFirstStore, type SyncOutboxOperation } from '../services/localFirstStore'
import './SyncCenter.css'

export function SyncCenter() {
  const asyncFinance = useAsyncFinanceOptional(); const offline = asyncFinance?.offline ?? false; const [operations, setOperations] = useState<SyncOutboxOperation[]>([]); const [snapshotDate, setSnapshotDate] = useState<string | null>(null); const { confirm, dialog: confirmDialog } = useConfirm()
  const refresh = useCallback(() => { void Promise.all([localFirstStore.outbox(), localFirstStore.latestSnapshot()]).then(([next, snapshot]) => { setOperations(next.sort((a, b) => b.createdAt.localeCompare(a.createdAt))); setSnapshotDate(snapshot?.syncedAt ?? null) }) }, [])
  useEffect(() => { refresh(); const timer = window.setInterval(refresh, 500); return () => window.clearInterval(timer) }, [refresh])
  const pending = operations.filter((operation) => operation.status === 'pending' || operation.status === 'syncing').length; const failed = operations.filter((operation) => operation.status === 'failed' || operation.status === 'conflict').length
  const retryOperation = (operation: SyncOutboxOperation) => { void localFirstStore.updateOperation({ ...operation, status: 'pending', lastError: null }).then(() => { refresh(); asyncFinance?.retry() }) }
  const discardOperation = async (operation: SyncOutboxOperation) => { if (!await confirm({ title: 'Discard local operation?', message: 'It will not be posted to the ledger.', confirmLabel: 'Discard operation' })) return; void localFirstStore.removeOperation(operation.operationId).then(refresh) }
  return <div className="page-stack sync-page"><PageHeader eyebrow="System" title="Sync Center" description="Review connection status, local changes, and receipt-processing behavior." action={<button className="btn btn--ghost" type="button" onClick={() => { asyncFinance?.retry(); refresh() }}>Retry sync</button>} /><div className="sync-grid"><Card><CardTitle>Connection</CardTitle><p role="status">{offline ? 'Server unreachable — using the latest local snapshot.' : 'Connected to Monikey'}</p><p className="muted">Last synced: {snapshotDate ? new Date(snapshotDate).toLocaleString() : 'Not available'}</p></Card><Card><CardTitle>Pending operations</CardTitle><p>{pending} waiting · {failed} needing attention</p>{operations.length === 0 ? <p className="muted">No local operations.</p> : <ul className="sync-operation-list">{operations.map((operation) => <li key={operation.operationId}><span>{operation.operationType.replaceAll('_', ' ')} · <strong>{operation.status}</strong>{operation.lastError ? ` · ${operation.lastError}` : ''}</span>{(operation.status === 'failed' || operation.status === 'conflict') && <span className="sync-operation-actions"><button type="button" className="crypto-text-action" onClick={() => retryOperation(operation)}>Retry</button><button type="button" className="crypto-text-action" onClick={() => void discardOperation(operation)}>Discard</button></span>}</li>)}</ul>}</Card><Card><CardTitle>Receipt OCR</CardTitle><p className="muted">Receipt images can be stored locally and processed in a browser worker. OCR results are suggestions only and require review before ledger entry.</p></Card></div>{confirmDialog}</div>
}
