/**
 * Object store interface for receipt file storage.
 * Implementations may use local filesystem, MinIO, S3, or other backends.
 * Storage is per-user and should not expose or trust client-supplied filenames.
 */

export interface ObjectStoreObject {
  /** Unique key under which the object was stored. */
  key: string
  /** Original filename (for metadata only; never used in path traversal). */
  originalFilename: string
  /** MIME type. */
  mimeType: string
  /** File size in bytes. */
  sizeBytes: number
  /** SHA256 hash of the stored content. */
  sha256: string
}

export interface ObjectStore {
  /**
   * Stores a file and returns metadata. The key is generated by the implementation
   * and must be randomized — never derived from the client-supplied filename.
   * Implementation must compute and return the SHA256 hash.
   */
  store(input: {
    /** File buffer contents. */
    buffer: Buffer
    /** Original filename for metadata purposes. */
    originalFilename: string
    /** MIME type. */
    mimeType: string
  }): Promise<ObjectStoreObject>

  /**
   * Retrieves a stored file by key. Caller is responsible for user isolation
   * (i.e., verify the user owns the receipt before retrieving).
   */
  retrieve(key: string): Promise<Buffer>

  /**
   * Deletes a stored file by key. Idempotent — deleting a non-existent key
   * should not throw.
   */
  delete(key: string): Promise<void>
}
