import type { FastifyInstance } from 'fastify'
import type { PrismaClient } from '@prisma/client'
import { z } from 'zod'
import { authGuard } from '../../common/auth/authGuard.js'
import { originCheckPreHandler } from '../../common/auth/originCheck.js'
import { applyRuleActions, matchesRule } from './rules.engine.js'
import { AppError } from '../../common/errors/appError.js'

const conditions = z.object({ merchantContains: z.string().max(120).optional(), merchantEquals: z.string().max(120).optional(), titleContains: z.string().max(120).optional(), minAmountMinor: z.string().regex(/^\d+$/).optional(), maxAmountMinor: z.string().regex(/^\d+$/).optional(), accountId: z.string().uuid().optional(), type: z.enum(['income', 'expense', 'transfer']).optional(), source: z.enum(['manual', 'ocr', 'recurring', 'import']).optional(), currencyCode: z.string().length(3).optional() })
const actions = z.object({ normalizedMerchant: z.string().max(120).optional(), categoryId: z.string().uuid().optional(), addTags: z.array(z.string().trim().min(1).max(40)).max(20).optional(), note: z.string().max(500).optional(), type: z.enum(['income', 'expense', 'transfer']).optional() })
const ruleInput = z.object({ name: z.string().trim().min(1).max(120), enabled: z.boolean().default(true), priority: z.number().int().min(0).max(10000).default(100), conditions, actions })
const previewTransaction = z.object({ title: z.string().trim().min(1).max(255), description: z.string().max(500).nullable().optional(), merchantName: z.string().max(120).nullable().optional(), amountMinor: z.string().regex(/^\d+$/), accountId: z.string().uuid().nullable().optional(), type: z.enum(['income', 'expense', 'transfer']), source: z.enum(['manual', 'ocr', 'recurring', 'import']), currencyCode: z.string().length(3) })
const previewInput = z.object({ transaction: previewTransaction, rule: ruleInput.pick({ conditions: true, actions: true }) })
const idSchema = z.object({ id: z.string().uuid() })
const idParamJson = { type: 'object', required: ['id'], properties: { id: { type: 'string', format: 'uuid' } } } as const
const conditionsJson = { type: 'object', additionalProperties: false, properties: { merchantContains: { type: 'string', maxLength: 120 }, merchantEquals: { type: 'string', maxLength: 120 }, titleContains: { type: 'string', maxLength: 120 }, minAmountMinor: { type: 'string', pattern: '^\\d+$' }, maxAmountMinor: { type: 'string', pattern: '^\\d+$' }, accountId: { type: 'string', format: 'uuid' }, type: { type: 'string', enum: ['income', 'expense', 'transfer'] }, source: { type: 'string', enum: ['manual', 'ocr', 'recurring', 'import'] }, currencyCode: { type: 'string', minLength: 3, maxLength: 3 } } } as const
const actionsJson = { type: 'object', additionalProperties: false, properties: { normalizedMerchant: { type: 'string', maxLength: 120 }, categoryId: { type: 'string', format: 'uuid' }, addTags: { type: 'array', maxItems: 20, items: { type: 'string', minLength: 1, maxLength: 40 } }, note: { type: 'string', maxLength: 500 }, type: { type: 'string', enum: ['income', 'expense', 'transfer'] } } } as const
const ruleBodyJson = { type: 'object', required: ['name', 'conditions', 'actions'], additionalProperties: false, properties: { name: { type: 'string', minLength: 1, maxLength: 120 }, enabled: { type: 'boolean', default: true }, priority: { type: 'integer', minimum: 0, maximum: 10000, default: 100 }, conditions: conditionsJson, actions: actionsJson } } as const
const ruleUpdateBodyJson = { ...ruleBodyJson, required: [] } as const
const ruleJson = { type: 'object', required: ['id', 'userId', 'name', 'enabled', 'priority', 'conditions', 'actions', 'createdAt', 'updatedAt'], properties: { id: { type: 'string', format: 'uuid' }, userId: { type: 'string', format: 'uuid' }, name: { type: 'string' }, enabled: { type: 'boolean' }, priority: { type: 'integer' }, conditions: conditionsJson, actions: actionsJson, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' } } } as const
const rulesJson = { type: 'array', items: ruleJson } as const
const errorJson = { type: 'object', required: ['error'], properties: { error: { type: 'object', required: ['code', 'message'], properties: { code: { type: 'string' }, message: { type: 'string' } } } } } as const
const previewTransactionJson = { type: 'object', required: ['title', 'amountMinor', 'type', 'source', 'currencyCode'], additionalProperties: false, properties: { title: { type: 'string', minLength: 1, maxLength: 255 }, description: { anyOf: [{ type: 'string', maxLength: 500 }, { type: 'null' }] }, merchantName: { anyOf: [{ type: 'string', maxLength: 120 }, { type: 'null' }] }, amountMinor: { type: 'string', pattern: '^\\d+$' }, accountId: { anyOf: [{ type: 'string', format: 'uuid' }, { type: 'null' }] }, type: { type: 'string', enum: ['income', 'expense', 'transfer'] }, source: { type: 'string', enum: ['manual', 'ocr', 'recurring', 'import'] }, currencyCode: { type: 'string', minLength: 3, maxLength: 3 } } } as const
const previewBodyJson = { type: 'object', required: ['transaction', 'rule'], additionalProperties: false, properties: { transaction: previewTransactionJson, rule: { type: 'object', required: ['conditions', 'actions'], additionalProperties: false, properties: { conditions: conditionsJson, actions: actionsJson } } } } as const
const previewResultJson = { ...previewTransactionJson, additionalProperties: false, properties: { ...previewTransactionJson.properties, normalizedMerchant: { type: 'string' }, categoryId: { type: 'string', format: 'uuid' }, note: { type: 'string' }, tags: { type: 'array', items: { type: 'string' } } } } as const
async function requirePreviewMinorString(req: { body?: unknown }) {
  const body = req.body as { transaction?: { amountMinor?: unknown } } | undefined
  if (typeof body?.transaction?.amountMinor !== 'string') throw new AppError('VALIDATION_ERROR', 'minor units must be a non-negative integer string', { statusCode: 400, field: 'transaction.amountMinor' })
}
export async function rulesRoutes(app: FastifyInstance, options: { prisma: PrismaClient; appOrigin: string }) {
  const { prisma } = options
  app.addHook('preHandler', authGuard({ prisma }))
  app.get('/rules', { schema: { response: { 200: rulesJson } } }, async (req) => prisma.transactionRule.findMany({ where: { userId: req.user!.id }, orderBy: [{ priority: 'asc' }, { createdAt: 'asc' }] }))
  app.post('/rules', { preHandler: originCheckPreHandler({ APP_ORIGIN: options.appOrigin }), schema: { body: ruleBodyJson, response: { 201: ruleJson } } }, async (req, reply) => reply.code(201).send(await prisma.transactionRule.create({ data: { userId: req.user!.id, ...ruleInput.parse(req.body) } })))
  app.patch<{ Params: { id: string } }>('/rules/:id', { preHandler: originCheckPreHandler({ APP_ORIGIN: options.appOrigin }), schema: { params: idParamJson, body: ruleUpdateBodyJson, response: { 200: ruleJson, 404: errorJson } } }, async (req, reply) => { const { id } = idSchema.parse(req.params); const owned = await prisma.transactionRule.findFirst({ where: { id, userId: req.user!.id } }); if (!owned) return reply.code(404).send({ error: { code: 'NOT_FOUND', message: 'Rule not found.' } }); return prisma.transactionRule.update({ where: { id }, data: ruleInput.partial().parse(req.body) }) })
  app.delete<{ Params: { id: string } }>('/rules/:id', { preHandler: originCheckPreHandler({ APP_ORIGIN: options.appOrigin }), schema: { params: idParamJson, response: { 204: { type: 'null' }, 404: errorJson } } }, async (req, reply) => { const { id } = idSchema.parse(req.params); const result = await prisma.transactionRule.deleteMany({ where: { id, userId: req.user!.id } }); return result.count ? reply.code(204).send() : reply.code(404).send({ error: { code: 'NOT_FOUND', message: 'Rule not found.' } }) })
  app.post('/rules/preview', { preValidation: requirePreviewMinorString, schema: { body: previewBodyJson, response: { 200: previewResultJson } } }, async (req) => { const input = previewInput.parse(req.body); const tx = { ...input.transaction, amountMinor: BigInt(input.transaction.amountMinor) }; const result = matchesRule(tx, input.rule.conditions) ? applyRuleActions(tx, input.rule.actions) : tx; return { ...result, amountMinor: result.amountMinor.toString() } })
}
